logging:
  level:
    org.springframework.web: DEBUG
  file: /var/www/html/tmtenure.log
server:
  port: 8588
spring:
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: update
  redis:
    host: redis
    port: 6379

  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: LeaduAbc123
    driver-class-name: org.postgresql.Driver
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
file:
  idCardPath: /var/www/html/idCard/
  requestIdCardPath: http://222.73.56.12:8588/files/download/idCard/
  faceImagePath: /var/www/html/faceImage/
  requestFaceImagePath: http://222.73.56.12:8588/files/download/faceImage/
  pdfPath: /var/www/html/pdf/
  requestPdfPath: http://222.73.56.12:8588/files/download/pdf/
  signedPdfPath: /var/www/html/signedPdf/
  requestSignedPdfPath: http://222.73.56.12:8588/files/download/signedPdf/

admin:
  auth: Basic d2VjaGF0OmxlYWR1MjAxNg==
request:
  adminServerUrl: http://wx.xftm.com:8089
  coreServerUrl: http://happyleasing.cn/TMZL/app/
message:
  userId: JJ2075
  password: 127628
  pszMsg: 验证码：xxxxxx，为保障您的账号安全，请勿泄露，有效期5分钟。
  iMobiCount: 1
  MsgId: 0
faceid:
  apiKey: FlaujBR73mcc0y0tCe7FocACriXm7Qqz
  apiSecret: -KN_NY5owumOwpBlRpPljogZmvzvZ6yw